version: "3.9"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    restart: unless-stopped
    command: >
      bash -c "python manage.py wait_db &&
      python manage.py migrate &&
      python manage.py create_users &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - ./backend/.env
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    restart: unless-stopped
    ports:
      - '6379:6379'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

